const reqestList = ["cro specialist",
"performance analyst",
"sea specialist",
"advertisment analyst",
"adwords analyst",
"conversion analyst",
"data analyst",
"google analytics",
"marketing analyst",
"marketing automation",
"power bi",
"sql developer",
"web analyst",
"conversion optimization",
"paid search analyst",
"looker",
"data professional",
"matomo",
"piwik pro",
"ads analyst",
"bigquery",
"google cloud platform",
"ecommerce analyst"]
